### ISSUE TITLE
Sovrapposizione commenti alle date in bassa risoluzione

### ISSUE THREAD

**Issue by Fedefreez** [Fedefreez/Buds-note#10]
Per mettere la data vicino al commento bisogna dare 80% di width al commento e 19% alle info del commento. Il problema é che il commento puó uscire dal div andando sotto la data se la risoluzione é bassa.

**Comment by Fedefreez** [comment]
Per ora si sovrappone solo la prima riga alla data, sto investigando per individuare il problema.

**Comment by Edoebzd** [comment]
per le risoluzioni molto piccole arriverà l'update con la versione per telefono (magari lì non mettiamo proprio la data o robe simili)

**Comment by Fedefreez** [comment]
No la mettiamo, bisogna riorganizzare il sito e farlo anche per mobile.

**Comment by Fedefreez** [comment]
Non mi sembra ci siano più problemi.
