### ISSUE TITLE
Con certe risoluzioni tipo quella del pc di mio babbo si bugga il sito (credo che sia solo se si ha un certo rapporto)

### ISSUE THREAD

**Issue by Fedefreez** [Fedefreez/Buds-note#12]
Bisogna che brotha modifichi il sito per fare fittare bene il tutto.

**Comment by Fedefreez** [comment]
@Edoebzd questo devi guardarci tu.

**Comment by Leodom01** [comment]
È un problema che in teoria dovrebbe risolversi con l'implementazione di bootstrap

**Comment by Leodom01** [comment]
Vista l'orientamento mobile side di bootstrap e la sua ottima capacità di gestire risoluzioni diverse questo issue non sarà più un problema dal momento che usiamo bootstrap (almeno finché non usiamo risoluzioni troppo assurde).
So chiudo perché non è più un problema nella branch Shards-frontend
