### ISSUE TITLE
Visitando budsnote.ddns.net/notedb si puó navigare fra le cartelle degli utenti e i loro files

### ISSUE THREAD

**Issue by Fedefreez** [Fedefreez/Buds-note#14]
Da fixare
@Leodom01 io suggerirei di bloccare la directory, perché mettendo un index.php che ti reindirizza un puó comunque indovinare l'url, che dici? Nel caso tu sia d'accordo, guarda come farlo che l'ho dimenticato e sono via. Thx

**Comment by Leodom01** [comment]
Qui spiega come impedire il directory browsing, dovrebbe essere quello che ci serve ma devi farlo tu @Fedefreez perchè bisogna farlo dal server Apache

**Comment by Fedefreez** [comment]
Puoi farlo dalla shell @Leodom01, non hai mandato il link della cosa che lo spiega lol

**Comment by Leodom01** [comment]
Ho cercato e si chiama Directory Listing, noi dobbiamo quindi impedire il directory listing del nostro (tuo) server Apache. Ora cerco come si fa e lo faccio

**Comment by Leodom01** [comment]
Sistemato disabilitando il Directory Listing dal file etc/apache2/apache2.conf
Special thanks to indiani con un discutibile inglese che fanno video su Youtube 
Ora se provo a fare il directory listing su budsnote.ddns.net/notedb per esempio ottengo questo
![Cattura](https://user-images.githubusercontent.com/25131781/65785413-9a13c480-e154-11e9-8235-5174db48e4d1.PNG)

**Comment by Fedefreez** [comment]
Ora manca da reindirizzare in un file decente, il config somiglia a:
<VirtualHost *:80>
    ...
    <Directory /path/to/vhost/>
      RewriteEngine on
      RewriteBase /example2/
      RewriteRule ^(.*)$ http://www.example2.com/$1 [R=301]
    </Directory>
</VirtualHost>

**Comment by Leodom01** [comment]
Essenzialmente bisogna negare a tutti a parte al PHP il diritto di richiedere risorse tramite link, in modo che uno anche avendo il link esatto della risorsa o della pagina su bud's note non può accedere a quella risorsa a meno che non sia PHP a richiedere quella pagina.

**Comment by Fedefreez** [comment]
Inoltre redirectare se nel percorso della dir visitata c'é note-db.

**Comment by Fedefreez** [comment]
Fra poco provo con questo, sembra essere quello che ci serve.
http://httpd.apache.org/docs/2.4/mod/mod_alias.html

**Comment by Fedefreez** [comment]
Sono anche disponibili tutti i files in /var/www/html/main, serve un fix al piú presto, @mrcvxr prof lei sa come si fa? Ho cerca su internet ma non sembrano funzionare i metodi degli altri :/ (@Leodom01 guardaci quando hai tempo)

**Comment by Leodom01** [comment]
Linko qui sotto un paio di risorse da consultare e da cui provare (ora non riesco a modificare nulla siccome il server è spento)
- https://stackoverflow.com/questions/2530372/how-do-i-disable-directory-browsing
- https://support.qualityunit.com/496941-How-to-disable-directory-browsing-in-apache-configuration
- https://www.thesitewizard.com/apache/prevent-directory-listing-htaccess.shtml
- https://www.techrepublic.com/article/how-to-make-apache-more-secure-by-hiding-directory-folders/

**Comment by Leodom01** [comment]
Risolto modificando il file config di apache 2, volendo si può reindirizzare a una pagina di errore in caso di errore 403 quando qualcuno prova ad accedere ad una risorsa che non può vedere
