### ISSUE TITLE
Finestrella che scenda per selezione Ordina per

### ISSUE THREAD

**Issue by Leodom01** [Fedefreez/Buds-note#15]
Quando uno va a cercare una nota il campo da cercare va inserito il nome del campo da cui fare l'ordinamento deve inserire il nome del campo e deve conoscerlo bene a memoria.
Sarebbe più opportuno far scendere una finestrella con tutte le opzioni di ordinamento e l'utente può sceglierne solo uno

**Comment by Leodom01** [comment]
In realtà la finestrella c'è ma sembra che non abbia ereditato l'attributo css che hanno tutte le altre finestrelle anche solo due o tre righe sopra

**Comment by Fedefreez** [comment]
Non ho capito bene cosa vuoi fare

**Comment by Fedefreez** [comment]
Ok ho capito, appena posso la implemento. (anche se solo selezionando la casella si vedono le opzioni)

**Comment by Fedefreez** [comment]
In ogni caso questo é un duplicato della carta aggiunta da @Edoebzd  nel progetto.

**Comment by Fedefreez** [comment]
Risolto commit 9c5499510610101dc9fc10d183036e16dc19a8d1
