### ISSUE TITLE
Commenti non vanno a capo

### ISSUE THREAD

**Issue by Leodom01** [Fedefreez/Buds-note#16]
I commenti non vanno a capo quando uno scrive il commento e nella text area mette invio quando poi il commento viene pubblicato non sono rispettati gli a capo

**Comment by Fedefreez** [comment]
Ci guardo appena posso.

**Comment by Fedefreez** [comment]
In ogni caso ricaricando la pagina gli a capo sono rispettati, é una cosa del js.

**Comment by Fedefreez** [comment]
Duplicate of #10

**Comment by Fedefreez** [comment]
Risolto
