### ISSUE TITLE
Votazione feature

### ISSUE THREAD

**Issue by Fedefreez** [Fedefreez/Buds-note#17]
Abbiamo le pagine subj e dept che dovrebbero mostrare tutte le note relative a quello che rappresentano, tuttavia non sono mai state completate. Votiamo per chi vorrebbe completarle/rimuoverle. Io mi astengo.

**Comment by Edoebzd** [comment]
non so, se non le facciamo bisogna cavare il pulsante dalla ricerca

**Comment by Leodom01** [comment]
Io le aggiungerei, tanto le funzioni php sono quasi tutte dentro funs.php, e quelle che mancano sono quasi copia incolla da quelle delle query generiche per le note

**Comment by Fedefreez** [comment]
Appena ho tempo le sistemo.
