### ISSUE TITLE
Gli hashtags mel titolo della nota la fanno buggare, (anche se é solo l'url che fallisce, credo)

### ISSUE THREAD

**Issue by Fedefreez** [Fedefreez/Buds-note#19]
Appena ho tempo investigo per trovare la causa, che probabilmente é htmlspecialchars() eseguita su $_GET["title"].
@Leodom01 cosa dici?

**Comment by Fedefreez** [comment]
Questo é stato fixato, ora l'aggiunta delle immagini non funziona, sto ancora investigando per trovare il problema.

**Comment by Fedefreez** [comment]
Modificando il titolo della nota l'url viene composto male, sto cercando di risolvere anche questo problema.

**Comment by Leodom01** [comment]
A questo punto dovrebbe essere risolto questo issue giusto? 
Posso chiuderlo con il mio ultimo commit ?

**Comment by Fedefreez** [comment]
Prima dobbiamo migrare :>>>

**Comment by Fedefreez** [comment]
Risolto commit 09f76970d08b0154d0f5e2631f34a9d38186176a
